@RestResource(urlMapping='/secureApexRest')
global with sharing class SecureApexRest {
    @HttpGet
    global static Contact doGet(){
        Contact result;
        try{
        Id recordId = RestContext.request.params.get('id');
        
        if (recordId == null){
            throw new FunctionalException('Id parameter is required');
        }

            List<Contact> results = [SELECT id, Name, Secret_Key__c FROM Contact WHERE Id = :recordId WITH SECURITY_ENFORCED];
            if (!results.isEmpty()) {
                result = results[0];
            }
            else
            throw new SecurityException('You don\'t have access to all contact fields required to use this API');
        
        
        }
        catch (System.QueryException e){
            
        }
        return result;
    }
    public class FunctionalException extends Exception{}
    public class SecurityException extends Exception{}
}